language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install .[tests]

script:
  - pytest tests/unit --cov=probflow

after_success:
  - bash < (curl -s https://codecov.io/bash)